version: "3"
services:
  web:
    image: nginx:latest
    container_name: webappsone
    ports:
      - "9080:80"
    volumes:
      - ./app/:/usr/share/nginx/html
      #- ./config:/etc/nginx/ 
        #entrypoint: [ "bash", "-c",  "nginx", "-g", "daemon off;"]
    restart: always
    healthcheck:
        test: curl --fail http://localhost || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 10s
