version: '3'
volumes:
  grafana-storage: {}
  prometheus-data: {}
  alertmanager-data: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./recording-rules.yml:/etc/prometheus/recording-rules.yml
      - ./alerting-rules.yml:/etc/prometheus/alerting-rules.yml
      - ./rule.yaml:/etc/prometheus/rule.yaml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana


  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - '9093:9093'
    volumes:
      - alertmanager-data:/data

