global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['192.168.30:9093']
      scheme: http
      timeout: 10s
      api_version: v1
rule_files:
  - rule.yaml
  - alerting-rules.yml
  - recording-rules.yml

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090
  - job_name: Linux-Monitoring # Change to whatever you like
    static_configs:
      - targets: ['192.168.0.39:9100', '192.168.0.34:9100', '192.168.0.35:9100', '192.168.0.36:9100', '192.168.0.30:9100']
