version: '3'
services:
  nginx:
    image: abramdocker/nginx-proxy:v2
    ports:
      - 80:80
    restart: always
    container_name: nginx-base
  jenkins:
    build: ./
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    depends_on:
      - nginx
    volumes:
      - ./jenkins-vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins-vol:
