---
- hosts: endpoint
  become: true
  tasks:
    - name: Clone GitHub repository
      ansible.builtin.command: git clone https://github.com/abraham218/abraham-repos.git
      args:
        chdir: /workspace/ansible/
